#!/usr/bin/env ruby

require 'pathname'


current_file,  = Pathname.new(ARGV[0])
project_path = Pathname.getwd
relative = current_file.relative_path_from(project_path)
target = relative.sub_ext('').to_s.gsub('/', '.')
executable = project_path + 'build' + relative.to_s.split('/')[0] + target

`make -C build #{target} && #{executable}`
